#ifndef H_REGISTRIES
#define H_REGISTRIES

#include <stdint.h>

extern uint8_t registries_bin[5718];

extern uint8_t B_to_I[256]; // Block-to-item mapping
extern uint8_t I_to_B[256]; // Item-to-block mapping
extern uint16_t block_palette[256]; // Block palette

// Block identifiers
#define B_acacia_hanging_sign 206
#define B_acacia_leaves 91
#define B_acacia_log 52
#define B_acacia_planks 17
#define B_acacia_pressure_plate 222
#define B_acacia_sapling 29
#define B_acacia_sign 192
#define B_acacia_wood 74
#define B_air 0
#define B_allium 157
#define B_andesite 6
#define B_azalea_leaves 96
#define B_azure_bluet 158
#define B_bamboo_block 59
#define B_bamboo_hanging_sign 214
#define B_bamboo_mosaic 24
#define B_bamboo_planks 23
#define B_bamboo_pressure_plate 227
#define B_bamboo_sign 198
#define B_basalt 244
#define B_bedrock 34
#define B_birch_hanging_sign 205
#define B_birch_leaves 89
#define B_birch_log 50
#define B_birch_planks 15
#define B_birch_pressure_plate 220
#define B_birch_sapling 27
#define B_birch_sign 191
#define B_birch_wood 72
#define B_black_bed 124
#define B_black_wool 152
#define B_blue_bed 120
#define B_blue_orchid 156
#define B_blue_wool 148
#define B_bookshelf 173
#define B_bricks 171
#define B_brown_bed 121
#define B_brown_mushroom 167
#define B_brown_wool 149
#define B_bush 132
#define B_cactus 235
#define B_cactus_flower 236
#define B_cake 250
#define B_carved_pumpkin 248
#define B_cherry_hanging_sign 207
#define B_cherry_leaves 92
#define B_cherry_log 53
#define B_cherry_planks 18
#define B_cherry_pressure_plate 223
#define B_cherry_sapling 30
#define B_cherry_sign 193
#define B_cherry_wood 75
#define B_chest 181
#define B_chiseled_bookshelf 174
#define B_chiseled_sandstone 106
#define B_clay 237
#define B_coal_ore 45
#define B_coarse_dirt 10
#define B_cobblestone 12
#define B_cobblestone_stairs 202
#define B_cobweb 128
#define B_cornflower 164
#define B_crafting_table 185
#define B_creaking_heart 179
#define B_crimson_hanging_sign 211
#define B_cut_sandstone 107
#define B_cyan_bed 118
#define B_cyan_wool 146
#define B_dandelion 153
#define B_dark_oak_hanging_sign 209
#define B_dark_oak_leaves 93
#define B_dark_oak_log 54
#define B_dark_oak_planks 19
#define B_dark_oak_pressure_plate 224
#define B_dark_oak_sapling 31
#define B_dark_oak_sign 195
#define B_dark_oak_wood 76
#define B_dead_bush 131
#define B_deepslate_coal_ore 46
#define B_deepslate_diamond_ore 183
#define B_deepslate_gold_ore 42
#define B_deepslate_iron_ore 44
#define B_deepslate_lapis_ore 102
#define B_deepslate_redstone_ore 229
#define B_detector_rail 126
#define B_diamond_block 184
#define B_diamond_ore 182
#define B_diorite 4
#define B_dirt 9
#define B_dispenser 104
#define B_farmland 187
#define B_fern 130
#define B_flowering_azalea_leaves 97
#define B_furnace 188
#define B_glass 100
#define B_glowstone 247
#define B_gold_block 169
#define B_gold_ore 41
#define B_granite 2
#define B_grass_block 8
#define B_gravel 39
#define B_gray_bed 116
#define B_gray_wool 144
#define B_green_bed 122
#define B_green_wool 150
#define B_ice 233
#define B_iron_block 170
#define B_iron_door 217
#define B_iron_ore 43
#define B_jack_o_lantern 249
#define B_jukebox 239
#define B_jungle_hanging_sign 208
#define B_jungle_leaves 90
#define B_jungle_log 51
#define B_jungle_planks 16
#define B_jungle_pressure_plate 221
#define B_jungle_sapling 28
#define B_jungle_sign 194
#define B_jungle_wood 73
#define B_ladder 200
#define B_lapis_block 103
#define B_lapis_ore 101
#define B_lever 215
#define B_light_blue_bed 112
#define B_light_blue_stained_glass 255
#define B_light_blue_wool 140
#define B_light_gray_bed 117
#define B_light_gray_wool 145
#define B_lily_of_the_valley 166
#define B_lime_bed 114
#define B_lime_wool 142
#define B_magenta_bed 111
#define B_magenta_stained_glass 254
#define B_magenta_wool 139
#define B_mangrove_hanging_sign 213
#define B_mangrove_leaves 95
#define B_mangrove_log 56
#define B_mangrove_planks 22
#define B_mangrove_pressure_plate 226
#define B_mangrove_propagule 33
#define B_mangrove_roots 57
#define B_mangrove_sign 197
#define B_mangrove_wood 77
#define B_mossy_cobblestone 175
#define B_muddy_mangrove_roots 58
#define B_nether_gold_ore 47
#define B_netherrack 241
#define B_note_block 108
#define B_oak_door 199
#define B_oak_fence 240
#define B_oak_hanging_sign 203
#define B_oak_leaves 87
#define B_oak_log 48
#define B_oak_planks 13
#define B_oak_pressure_plate 218
#define B_oak_sapling 25
#define B_oak_sign 189
#define B_oak_stairs 180
#define B_oak_wood 70
#define B_obsidian 176
#define B_orange_bed 110
#define B_orange_stained_glass 253
#define B_orange_tulip 160
#define B_orange_wool 138
#define B_oxeye_daisy 163
#define B_pale_oak_hanging_sign 210
#define B_pale_oak_leaves 94
#define B_pale_oak_log 55
#define B_pale_oak_planks 21
#define B_pale_oak_pressure_plate 225
#define B_pale_oak_sapling 32
#define B_pale_oak_sign 196
#define B_pale_oak_wood 20
#define B_pink_bed 115
#define B_pink_tulip 162
#define B_pink_wool 143
#define B_piston 136
#define B_podzol 11
#define B_polished_andesite 7
#define B_polished_basalt 245
#define B_polished_diorite 5
#define B_polished_granite 3
#define B_poppy 155
#define B_powered_rail 125
#define B_purple_bed 119
#define B_purple_wool 147
#define B_rail 201
#define B_red_bed 123
#define B_red_mushroom 168
#define B_red_sand 38
#define B_red_tulip 159
#define B_red_wool 151
#define B_redstone_ore 228
#define B_redstone_torch 230
#define B_repeater 251
#define B_sand 36
#define B_sandstone 105
#define B_seagrass 135
#define B_short_dry_grass 133
#define B_short_grass 129
#define B_snow 232
#define B_snow_block 234
#define B_soul_sand 242
#define B_soul_soil 243
#define B_soul_torch 246
#define B_spawner 178
#define B_sponge 98
#define B_spruce_hanging_sign 204
#define B_spruce_leaves 88
#define B_spruce_log 49
#define B_spruce_planks 14
#define B_spruce_pressure_plate 219
#define B_spruce_sapling 26
#define B_spruce_sign 190
#define B_spruce_wood 71
#define B_sticky_piston 127
#define B_stone 1
#define B_stone_button 231
#define B_stone_pressure_plate 216
#define B_stripped_acacia_log 63
#define B_stripped_acacia_wood 82
#define B_stripped_bamboo_block 69
#define B_stripped_birch_log 61
#define B_stripped_birch_wood 80
#define B_stripped_cherry_log 64
#define B_stripped_cherry_wood 83
#define B_stripped_dark_oak_log 65
#define B_stripped_dark_oak_wood 84
#define B_stripped_jungle_log 62
#define B_stripped_jungle_wood 81
#define B_stripped_mangrove_log 68
#define B_stripped_mangrove_wood 86
#define B_stripped_oak_log 67
#define B_stripped_oak_wood 78
#define B_stripped_pale_oak_log 66
#define B_stripped_pale_oak_wood 85
#define B_stripped_spruce_log 60
#define B_stripped_spruce_wood 79
#define B_sugar_cane 238
#define B_suspicious_gravel 40
#define B_suspicious_sand 37
#define B_tall_dry_grass 134
#define B_tnt 172
#define B_torch 177
#define B_torchflower 154
#define B_warped_hanging_sign 212
#define B_water 35
#define B_wet_sponge 99
#define B_wheat 186
#define B_white_bed 109
#define B_white_stained_glass 252
#define B_white_tulip 161
#define B_white_wool 137
#define B_wither_rose 165
#define B_yellow_bed 113
#define B_yellow_wool 141

// Item identifiers
#define I_acacia_leaves 186
#define I_acacia_log 138
#define I_acacia_planks 40
#define I_acacia_sapling 53
#define I_acacia_wood 175
#define I_air 0
#define I_allium 234
#define I_amethyst_block 88
#define I_ancient_debris 82
#define I_andesite 6
#define I_azalea 205
#define I_azalea_leaves 191
#define I_azure_bluet 235
#define I_bamboo_block 147
#define I_bamboo_mosaic 48
#define I_bamboo_planks 45
#define I_bedrock 58
#define I_birch_leaves 184
#define I_birch_log 136
#define I_birch_planks 38
#define I_birch_sapling 51
#define I_birch_wood 173
#define I_black_wool 228
#define I_blue_orchid 233
#define I_blue_wool 224
#define I_brown_mushroom 247
#define I_brown_wool 225
#define I_budding_amethyst 89
#define I_bush 204
#define I_calcite 11
#define I_cherry_leaves 187
#define I_cherry_log 139
#define I_cherry_planks 41
#define I_cherry_sapling 54
#define I_cherry_wood 176
#define I_chiseled_copper 98
#define I_chiseled_sandstone 199
#define I_chiseled_tuff 16
#define I_chiseled_tuff_bricks 25
#define I_closed_eyeblossom 231
#define I_coal_block 83
#define I_coal_ore 64
#define I_coarse_dirt 29
#define I_cobbled_deepslate 9
#define I_cobblestone 35
#define I_cobweb 201
#define I_copper_block 91
#define I_copper_ore 68
#define I_cornflower 241
#define I_crimson_fungus 249
#define I_crimson_hyphae 180
#define I_crimson_nylium 33
#define I_crimson_planks 46
#define I_crimson_roots 251
#define I_crimson_stem 145
#define I_cut_copper 102
#define I_cut_copper_slab 110
#define I_cut_copper_stairs 106
#define I_cut_sandstone 200
#define I_cyan_wool 222
#define I_dandelion 229
#define I_dark_oak_leaves 188
#define I_dark_oak_log 141
#define I_dark_oak_planks 42
#define I_dark_oak_sapling 55
#define I_dark_oak_wood 178
#define I_dead_bush 207
#define I_deepslate 8
#define I_deepslate_coal_ore 65
#define I_deepslate_copper_ore 69
#define I_deepslate_diamond_ore 79
#define I_deepslate_emerald_ore 75
#define I_deepslate_gold_ore 71
#define I_deepslate_iron_ore 67
#define I_deepslate_lapis_ore 77
#define I_deepslate_redstone_ore 73
#define I_diamond_block 93
#define I_diamond_ore 78
#define I_diorite 4
#define I_dirt 28
#define I_dripstone_block 26
#define I_emerald_ore 74
#define I_exposed_chiseled_copper 99
#define I_exposed_copper 95
#define I_exposed_cut_copper 103
#define I_exposed_cut_copper_slab 111
#define I_exposed_cut_copper_stairs 107
#define I_fern 203
#define I_firefly_bush 208
#define I_flowering_azalea 206
#define I_flowering_azalea_leaves 192
#define I_glass 195
#define I_gold_block 92
#define I_gold_ore 70
#define I_granite 2
#define I_grass_block 27
#define I_gravel 63
#define I_gray_wool 220
#define I_green_wool 226
#define I_heavy_core 87
#define I_iron_block 90
#define I_iron_ore 66
#define I_jungle_leaves 185
#define I_jungle_log 137
#define I_jungle_planks 39
#define I_jungle_sapling 52
#define I_jungle_wood 174
#define I_lapis_block 197
#define I_lapis_ore 76
#define I_light_blue_wool 216
#define I_light_gray_wool 221
#define I_lily_of_the_valley 242
#define I_lime_wool 218
#define I_magenta_wool 215
#define I_mangrove_leaves 190
#define I_mangrove_log 142
#define I_mangrove_planks 44
#define I_mangrove_propagule 57
#define I_mangrove_roots 143
#define I_mangrove_wood 179
#define I_mud 32
#define I_muddy_mangrove_roots 144
#define I_nether_gold_ore 80
#define I_nether_quartz_ore 81
#define I_nether_sprouts 253
#define I_netherite_block 94
#define I_oak_leaves 182
#define I_oak_log 134
#define I_oak_planks 36
#define I_oak_sapling 49
#define I_oak_wood 171
#define I_open_eyeblossom 230
#define I_orange_tulip 237
#define I_orange_wool 214
#define I_oxeye_daisy 240
#define I_oxidized_chiseled_copper 101
#define I_oxidized_copper 97
#define I_oxidized_cut_copper 105
#define I_oxidized_cut_copper_slab 113
#define I_oxidized_cut_copper_stairs 109
#define I_pale_oak_leaves 189
#define I_pale_oak_log 140
#define I_pale_oak_planks 43
#define I_pale_oak_sapling 56
#define I_pale_oak_wood 177
#define I_pink_tulip 239
#define I_pink_wool 219
#define I_pitcher_plant 245
#define I_podzol 30
#define I_polished_andesite 7
#define I_polished_deepslate 10
#define I_polished_diorite 5
#define I_polished_granite 3
#define I_polished_tuff 17
#define I_polished_tuff_slab 18
#define I_polished_tuff_stairs 19
#define I_polished_tuff_wall 20
#define I_poppy 232
#define I_purple_wool 223
#define I_raw_copper_block 85
#define I_raw_gold_block 86
#define I_raw_iron_block 84
#define I_red_mushroom 248
#define I_red_sand 62
#define I_red_tulip 236
#define I_red_wool 227
#define I_redstone_ore 72
#define I_rooted_dirt 31
#define I_sand 59
#define I_sandstone 198
#define I_sea_pickle 212
#define I_seagrass 211
#define I_short_dry_grass 209
#define I_short_grass 202
#define I_sponge 193
#define I_spore_blossom 246
#define I_spruce_leaves 183
#define I_spruce_log 135
#define I_spruce_planks 37
#define I_spruce_sapling 50
#define I_spruce_wood 172
#define I_stone 1
#define I_stripped_acacia_log 152
#define I_stripped_acacia_wood 163
#define I_stripped_bamboo_block 170
#define I_stripped_birch_log 150
#define I_stripped_birch_wood 161
#define I_stripped_cherry_log 153
#define I_stripped_cherry_wood 164
#define I_stripped_crimson_hyphae 168
#define I_stripped_crimson_stem 157
#define I_stripped_dark_oak_log 154
#define I_stripped_dark_oak_wood 165
#define I_stripped_jungle_log 151
#define I_stripped_jungle_wood 162
#define I_stripped_mangrove_log 156
#define I_stripped_mangrove_wood 167
#define I_stripped_oak_log 148
#define I_stripped_oak_wood 159
#define I_stripped_pale_oak_log 155
#define I_stripped_pale_oak_wood 166
#define I_stripped_spruce_log 149
#define I_stripped_spruce_wood 160
#define I_stripped_warped_hyphae 169
#define I_stripped_warped_stem 158
#define I_suspicious_gravel 61
#define I_suspicious_sand 60
#define I_tall_dry_grass 210
#define I_tinted_glass 196
#define I_torchflower 244
#define I_tuff 12
#define I_tuff_brick_slab 22
#define I_tuff_brick_stairs 23
#define I_tuff_brick_wall 24
#define I_tuff_bricks 21
#define I_tuff_slab 13
#define I_tuff_stairs 14
#define I_tuff_wall 15
#define I_twisting_vines 255
#define I_warped_fungus 250
#define I_warped_hyphae 181
#define I_warped_nylium 34
#define I_warped_planks 47
#define I_warped_roots 252
#define I_warped_stem 146
#define I_waxed_chiseled_copper 118
#define I_waxed_copper_block 114
#define I_waxed_cut_copper 122
#define I_waxed_cut_copper_slab 130
#define I_waxed_cut_copper_stairs 126
#define I_waxed_exposed_chiseled_copper 119
#define I_waxed_exposed_copper 115
#define I_waxed_exposed_cut_copper 123
#define I_waxed_exposed_cut_copper_slab 131
#define I_waxed_exposed_cut_copper_stairs 127
#define I_waxed_oxidized_chiseled_copper 121
#define I_waxed_oxidized_copper 117
#define I_waxed_oxidized_cut_copper 125
#define I_waxed_oxidized_cut_copper_slab 133
#define I_waxed_oxidized_cut_copper_stairs 129
#define I_waxed_weathered_chiseled_copper 120
#define I_waxed_weathered_copper 116
#define I_waxed_weathered_cut_copper 124
#define I_waxed_weathered_cut_copper_slab 132
#define I_waxed_weathered_cut_copper_stairs 128
#define I_weathered_chiseled_copper 100
#define I_weathered_copper 96
#define I_weathered_cut_copper 104
#define I_weathered_cut_copper_slab 112
#define I_weathered_cut_copper_stairs 108
#define I_weeping_vines 254
#define I_wet_sponge 194
#define I_white_tulip 238
#define I_white_wool 213
#define I_wither_rose 243
#define I_yellow_wool 217

#endif
